[package]
name = "compost-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-hal = { version = "1.1.2", features = ["esp32c3", "unstable"] }
esp-backtrace = { version = "0.20.0", features = ["esp32c3", "panic-handler", "println"] }
esp-println = { version = "0.18.0", features = ["esp32c3", "jtag-serial"], default-features = false }
esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32c3"] }
embedded-hal = "1.0.0"
critical-section = "1.2.0"

esp-rtos = { version = "0.4.0", features = ["embassy", "esp32c3", "esp-alloc"] }
esp-radio = { version = "0.18.0", features = ["esp32c3", "wifi"] }
esp-alloc = "0.11.0"
embassy-executor = { version = "0.10.0", features = ["platform-riscv32", "executor-thread"] }
embassy-net = { version = "0.9.1", features = ["dhcpv4", "medium-ip", "tcp"] }
embassy-time = "0.5.0"

[profile.dev.package.esp-radio]
opt-level = 3
[profile.dev.package.esp-wifi]
opt-level = 3

[profile.release]
opt-level = "s"

[profile.release.package.esp-radio]
opt-level = 3