[package]
name = "compost-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-hal = { version = "1.1.2", features = ["esp32c3", "unstable"] }
esp-backtrace = { version = "0.20.0", features = ["esp32c3", "panic-handler", "println"] }
esp-println = { version = "0.18.0", features = ["esp32c3", "jtag-serial", "log-04"], default-features = false }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32c3"] }
embedded-hal = "1.0.0"
critical-section = "1.2.0"

esp-rtos = { version = "0.3.0", features = ["embassy", "esp32c3", "esp-alloc", "esp-radio"] }
esp-radio = { version = "0.18.0", features = ["esp32c3", "wifi"] }
esp-alloc = "0.10.0"

embassy-executor = { version = "0.10.0", features = ["executor-thread"] }
embassy-net = { version = "0.7.1", features = ["dhcpv4", "medium-ip", "tcp", "dns"] }
embassy-time = "0.5.0"

myrtio-mqtt = "0.3.0"
static_cell = "2.1.0"
heapless = "0.9.3"

[profile.dev.package.esp-radio]
opt-level = 3
[profile.release]
opt-level = "s"
[profile.release.package.esp-radio]
opt-level = 3